### BrandAvailable | 브랜드 입점
POST {{basic-url}}/brand/available
Authorization: Bearer eyJyZWdEYXRlIjoxNjc5NDI0MTM1NzM1LCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjpbIk1FTUJFUiJdLCJpZCI6Ijc4NTQiLCJ0b2tlblR5cGUiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTY3OTQ0NTczNX0.MeoauFXWyniCgMKSbNwk0l4fFi00rtaRUbMXOLqqWiQ
Content-Type: application/json

{
  "name": "gowl",
  "email": "this.email",
  "homepageUrl": "this.homepageUrl",
  "introduce": "this.introduce",
  "company": "this.company",
  "businessNumber": "1111111",
  "managerName": "this.managerName",
  "businessAddress": "this.businessAddress",
  "phoneNumber": "this.phoneNumber",
  "isAudit": "false"
}

### AuditAvailable | 브랜드 입점 심사
PUT {{basic-url}}/brand/audit/available/gowl

### BrandUpdate | 브랜드 업데이트
PUT {{basic-url}}/brand/update
Authorization: Bearer eyJyZWdEYXRlIjoxNjc5NDI0MTM1NzM1LCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjpbIk1FTUJFUiJdLCJpZCI6Ijc4NTQiLCJ0b2tlblR5cGUiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTY3OTQ0NTczNX0.MeoauFXWyniCgMKSbNwk0l4fFi00rtaRUbMXOLqqWiQ
Content-Type: application/json

{
  "name": "gowl",
  "email": "emailemail@gmail.com",
  "homepageUrl": "this.homepageUrl",
  "introduce": "my brand introduce",
  "company": "Hongpany",
  "businessNumber": "0010204040",
  "managerName": "HHI",
  "businessAddress": "Address",
  "phoneNumber": "00000000000"
}
