### SignUp | 회원가입

POST {{basic-url}}/members/signUp
Content-Type: application/json

{
  "email": "email1234@gmail.com",
  "id": "7854",
  "password": "password1234",
  "name": "name",
  "nickname": "nickname222",
  "weight": 71,
  "height": 180,
  "gender": "M",
  "age": 25,
  "phoneNumber" : "01000000000",
  "address": "address",
  "birthday": "2000-02-14T11:44:30.327959"
}

### SignUp | 회원가입

POST {{basic-url}}/members/signUp
Content-Type: application/json

{
  "email": "email1234@gmail.com",
  "id": "admin1020",
  "password": "admin1020@",
  "name": "관리자",
  "nickname": "관리자",
  "weight": 71,
  "height": 180,
  "gender": "M",
  "age": 25,
  "phoneNumber" : "01000000000",
  "address": "address",
  "birthday": "2000-02-14T11:44:30.327959"
}

### SignIn | 로그인

POST {{basic-url}}/members/signIn
Content-Type: application/json

{
  "id": "7854",
  "password": "password1234"
}

### ProfileUpdate | 프로필 업데이트

PATCH {{basic-url}}/members/1
Authorization: {{member-token}}
Content-Type: application/json

{
  "password": "password1234",
  "name": "name2222",
  "nickname": "nickname222323232",
  "email": "email1234@gmail.com",
  "weight": 71,
  "height": 180,
  "phoneNumber": "01000000000"
}

### PasswordChange | 패스워드 변경

PATCH {{basic-url}}/members/1/password
Authorization: {{member-token}}
Content-Type: application/json

{
  "currentPassword": "password1234",
  "newPassword": "pw12345678",
  "reNewPassword": "pw12345678"
}
