### SignUp | 회원가입

POST {{basic-url}}/member/signUp
Content-Type: application/json

{
  "email": "email1234@gmail.com",
  "id": "id12345",
  "password": "password1234",
  "name": "name",
  "nickname": "nickname222",
  "weight": 71,
  "height": 180,
  "gender": "M",
  "age": 25,
  "phoneNumber" : "01000000000",
  "address": "address",
  "birthday": "2000-01-01T11:44:30.327959"
}

### SignIn | 로그인

POST {{basic-url}}/member/signIn
Content-Type: application/json

{
  "id": "id12345",
  "password": "password1234"
}

### ProfileUpdate | 프로필 업데이트

PUT {{basic-url}}/member/update
Authorization: Bearer eyJyZWdEYXRlIjoxNjc1NjkxODU5OTQzLCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjpbIk1FTUJFUiJdLCJpZCI6ImlkMTIzNDUiLCJ0b2tlblR5cGUiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTY3NTcxMzQ1OX0.Yga8N8eeyxJ8BHxbVO6gEwlj5JWBB7PSpNaDLpy8Aa4
Content-Type: application/json

{
  "password": "password1234",
  "name": "name2222",
  "nickname": "nickname222",
  "email": "email1234@gmail.com",
  "weight": 71,
  "height": 180,
  "phoneNumber": "01000000000"
}

### PasswordChange | 패스워드 변경

PUT {{basic-url}}/member/pw/change
Authorization: Bearer eyJyZWdEYXRlIjoxNjc1MzM4MDE3NjM0LCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjpbIk1FTUJFUiJdLCJpZCI6ImlkMTIzNCIsInRva2VuVHlwZSI6IkFjY2Vzc1Rva2VuIiwiZXhwIjoxNjc1MzU5NjE3fQ.rsbtYaKY9WKAJRDR3mVU3efIR6LpR_RL3enJ6j7L4tE
Content-Type: application/json

{
  "currentPassword": "password1234",
  "newPassword": "pw12345678",
  "reNewPassword": "pw12345678"
}
