### RegistrationProduct | 상품 등록
POST {{basic-url}}/product/registration
Authorization: Bearer eyJyZWdEYXRlIjoxNjc5NDI0MTM1NzM1LCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjpbIk1FTUJFUiJdLCJpZCI6Ijc4NTQiLCJ0b2tlblR5cGUiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTY3OTQ0NTczNX0.MeoauFXWyniCgMKSbNwk0l4fFi00rtaRUbMXOLqqWiQ
Content-Type: application/json

{
  "name": "CHAGARI",
  "price": "50000",
  "category": "차가리 반팔티",
  "gender": "W",
  "stock": "200",
  "brandName": "gowl"
}

### AddProductOptions | 상품 정보 등록
POST {{basic-url}}/product/option/add/2
Content-Type: application/json

[
  {
    "size": "M",
    "color": "Red"
  },
  {
    "size": "L",
    "color": "Blue"
  }
]

### UpdateProduct | 상품 업데이트

PUT {{basic-url}}/product/update
Content-Type: application/json

{
  "productIdx": 1,
  "name": "OVANG GYRACEK 반팔",
  "price": "20000",
  "category": "반팔티",
  "gender": "M",
  "stock": "200"
}

### UpdateProductOptions | 상품 정보 업데이트
PUT {{basic-url}}/product/option/update/1
Content-Type: application/json

[
  {
    "size": "S",
    "color": "Blue"
  },
  {
    "size": "M",
    "color": "Red"
  },
  {
    "size": "L",
    "color": "Blue"
  },
  {
    "size": "XL",
    "color": "Blue"
  }
]

### UpdateIsSoldOut | 상품 품절 업데이트
PUT {{basic-url}}/product/soldOut/1

### GetProduct | 상품 단일 조회
GET {{basic-url}}/product/1

### GetProducts | 상품 전체 태그 조회
GET {{basic-url}}/product/?page=0&size=10&name=OVANG GYRACEK 반팔&gender=M

### DeleteProduct | 상품 삭제
DELETE {{basic-url}}/product/1
