### RegistrationProduct | 상품 등록
POST {{basic-url}}/products
Authorization: {{member-token}}
Content-Type: application/json

{
  "name": "CHAGARI",
  "price": "50000",
  "category": "차가리 반팔티",
  "gender": "W",
  "stock": "200",
  "brandName": "gwol"
}

### RegistrationProduct | 상품 등록 (브랜드 없는
POST {{basic-url}}/products
Authorization: {{member-token}}
Content-Type: application/json

{
  "name": "CHAGARI",
  "price": "50000",
  "category": "차가리 반팔티",
  "gender": "W",
  "stock": "200"
}

### AddProductOptions | 상품 정보 등록
POST {{basic-url}}/products/option/2
Content-Type: application/json
Authorization: {{member-token}}

[
  {
    "size": "M",
    "color": "Red"
  },
  {
    "size": "L",
    "color": "Blue"
  }
]

### UpdateProduct | 상품 업데이트

PUT {{basic-url}}/products/
Content-Type: application/json
Authorization: {{member-token}}

{
  "productIdx": 1,
  "name": "차가리 반팔티",
  "price": "20000",
  "category": "반팔티",
  "gender": "M",
  "stock": "200"
}

### UpdateProductOptions | 상품 정보 업데이트
PUT {{basic-url}}/products/option/1
Content-Type: application/json
Authorization: {{member-token}}

[
  {
    "size": "S",
    "color": "Blue"
  },
  {
    "size": "M",
    "color": "Red"
  },
  {
    "size": "L",
    "color": "Blue"
  },
  {
    "size": "XL",
    "color": "Blue"
  }
]

### UpdateIsSoldOut | 상품 품절 업데이트
PUT {{basic-url}}/products/sold-out/1
Authorization: {{member-token}}

### GetProduct | 상품 단일 조회
GET {{basic-url}}/products/1
Authorization: {{member-token}}

### GetProductOption | 상품 옵션 조회
GET {{basic-url}}/products/option/1
Authorization: {{member-token}}

### GetProducts | 상품 전체 태그 조회
GET {{basic-url}}/products/?page=0&size=10
Authorization: {{member-token}}

### DeleteProduct | 상품 삭제
DELETE {{basic-url}}/products/1
Authorization: {{member-token}}
