### RegistrationProduct | 상품 등록
POST {{basic-url}}/product/registration
Authorization: Bearer eyJyZWdEYXRlIjoxNjc1NjkxODU5OTQzLCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjpbIk1FTUJFUiJdLCJpZCI6ImlkMTIzNDUiLCJ0b2tlblR5cGUiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTY3NTcxMzQ1OX0.Yga8N8eeyxJ8BHxbVO6gEwlj5JWBB7PSpNaDLpy8Aa4
Content-Type: application/json

{
  "name": "CHAGARI",
  "price": "50000",
  "category": "차가리 반팔티",
  "gender": "W",
  "stock": "200",
  "brandName": "gowl",
  "color": ["검정", "흰색"],
  "size": ["M", "L"]
}

### UpdateProduct | 상품 업데이트

PUT {{basic-url}}/product/update
Authorization: Bearer eyJyZWdEYXRlIjoxNjc1NjkxODU5OTQzLCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjpbIk1FTUJFUiJdLCJpZCI6ImlkMTIzNDUiLCJ0b2tlblR5cGUiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTY3NTcxMzQ1OX0.Yga8N8eeyxJ8BHxbVO6gEwlj5JWBB7PSpNaDLpy8Aa4
Content-Type: application/json

{
  "productId": 1,
  "name": "OVANG GYRACEK 반팔",
  "price": "20000",
  "category": "반팔티",
  "gender": "M",
  "stock": "200",
  "color": ["검정", "흰색"],
  "size": ["M", "L"]
}

### UpdateIsSoldOut | 상품 품절 업데이트
PUT {{basic-url}}/product/soldOut/OVANG GYRACEK 반팔

### GetProduct | 상품 단일 조회
GET {{basic-url}}/product/1

### GetProducts | 상품 전체 태그 조회
GET {{basic-url}}/product/?page=0&size=10&name=CHAGARI&gender=W
